plugins:
- standard
- node
- promise
- security

extends:
- eslint:recommended
- plugin:node/recommended
- plugin:promise/recommended
- plugin:security/recommended

parserOptions:
  ecmaVersion: 6

env:
  node: true
  es6: true
