language: node_js

dist: trusty

node_js:
- "10"

install: npm install --ignore-scripts
cache:
  directories:
  - node_modules

env:
  - NODE10=true

matrix:
  fast_finish: true

stages:
- precache # warm up cache for default Node.js version
- build
- lint # lint code and docs

jobs:
  include:
  - stage: precache
    script: true
    
  - stage: build
    script: 'tsc'

  - stage: lint
    script: 'npm run lint'
